"""UrbanPulse AI - Orchestration Service (Agent Gateway)"""

import os
import sys
from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from pydantic import BaseModel

# Add project root to sys.path to resolve 'agents' import
project_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from agents.graph import create_urbanpulse_graph

app = FastAPI(title="UrbanPulse AI - Orchestration Service", version="0.1.0")

# Compile LangGraph agent workflow once on startup
workflow = create_urbanpulse_graph()


class QueryRequest(BaseModel):
    query: str
    location: dict | None = None
    context: dict = {}


class QueryResponse(BaseModel):
    query: str
    explanation: str
    recommendations: list[str] = []
    data: dict = {}
    agents_used: list[str] = []


@app.get("/health")
async def health():
    return {"status": "healthy", "service": "orchestration"}


@app.post("/api/v1/query", response_model=QueryResponse)
async def process_query(request: QueryRequest):
    """Process a natural language query through the agent graph."""
    initial_state = {
        "messages": [],
        "query": request.query,
        "location": request.location,
        "time_range": None,
        "traffic_data": None,
        "weather_data": None,
        "incident_data": None,
        "risk_assessment": None,
        "forecast": None,
        "simulation_result": None,
        "explanation": None,
        "recommendations": [],
        "retrieved_docs": [],
        "routing_decision": None
    }

    # Execute LangGraph workflow asynchronously
    result = await workflow.ainvoke(initial_state)

    # Collect any data states generated by agents
    data_payload = {
        "traffic_data": result.get("traffic_data"),
        "weather_data": result.get("weather_data"),
        "incident_data": result.get("incident_data"),
        "simulation_result": result.get("simulation_result"),
        "retrieved_docs": result.get("retrieved_docs"),
        "location": result.get("location")
    }

    # Track agents that were executed
    routing_decision = result.get("routing_decision", "explain")
    agents_used = ["router"]
    if routing_decision != "explain":
        agent_names = {
            "traffic": "traffic_reasoner_agent",
            "route": "mobility_planner_agent",
            "policy": "policy_retrieval_agent",
            "simulate": "simulation_agent"
        }
        agents_used.append(agent_names.get(routing_decision, f"{routing_decision}_agent"))
    agents_used.append("narrative_agent")

    return QueryResponse(
        query=request.query,
        explanation=result.get("explanation") or "Analysis completed, no narrative output.",
        recommendations=result.get("recommendations") or [],
        data={k: v for k, v in data_payload.items() if v is not None},
        agents_used=agents_used,
    )


@app.post("/api/v1/simulate")
async def run_simulation(scenario: dict):
    """Run a what-if simulation scenario by executing the graph simulation flow."""
    initial_state = {
        "messages": [],
        "query": scenario.get("query", "Simulate closure"),
        "location": None,
        "time_range": None,
        "traffic_data": None,
        "weather_data": None,
        "incident_data": None,
        "risk_assessment": None,
        "forecast": None,
        "simulation_result": None,
        "explanation": None,
        "recommendations": [],
        "retrieved_docs": [],
        "routing_decision": "simulate"
    }

    result = await workflow.ainvoke(initial_state)
    return {
        "scenario": scenario,
        "result": result.get("explanation"),
        "impact": result.get("simulation_result") or {},
    }


@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    """WebSocket for real-time updates."""
    await websocket.accept()
    try:
        while True:
            data = await websocket.receive_text()
            # Echo for connection testing
            await websocket.send_json({"type": "ack", "data": data})
    except WebSocketDisconnect:
        pass
